package main

// DO NOT EDIT, this file is generated by hover at compile-time for the flutter_printer plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	flutter_printer "github.com/itMicmouse/flutter_printer/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&flutter_printer.FlutterPrinterPlugin{}))
}
